spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
server.servlet.session.cookie.secure=true
redauxilio.security.force-https=true
server.forward-headers-strategy=framework
